version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 727646474370.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t mohan-api .
      - docker tag mohan-api:latest 727646474370.dkr.ecr.us-east-1.amazonaws.com/mohan-api:latest
      - docker push 727646474370.dkr.ecr.us-east-1.amazonaws.com/mohan-api:latest
artifacts:
  files: '**/*'
